zohosalesiq.settings:
  type: config_object
  label: 'Zoho SalesIQ Chat settings'
  mapping:
    zohosalesiq_widget_code:
      type: text
      label: 'Zoho SalesIQ Chat Widget code'
    zohosalesiq_enabled:
      type: integer
      label: 'Show Zoho SalesIQ Chat widget'
    zohosalesiq_show_in:
      type: integer
      label: 'Show Zoho SalesIQ Chat widget on specific page'
    
